version: "3"

services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - blog-networks

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    networks:
      - blog-networks
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest  
    ports:
      - "27017:27017"  
    networks:
      - blog-networks
    volumes:
      - mongo-data:/data/db
      
networks:
  blog-networks:
    driver: bridge

volumes:
  mongo-data:
    driver: local  # Persist MongoDB data locally