version: "3"

services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - blog-networks

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    networks:
      - blog-networks
      
networks:
  blog-networks:
    driver: bridge