# Default values for my-blog-app-hart.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ankitjindal9404/MERN-Blog-Platform
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "18245071628"

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
